version: '3.4'

services:
     catalogdb:
         image: mongo

     catelog.api:
        image: ${DOCKER_REGISTRY-}catelogapi
        build:
            context: .
            dockerfile: src/Catelog/Catelog.API/Dockerfile